### PR TITLE
Release v1.7.0

### PR DESCRIPTION
**Pull request by GalRogozinski**
This is the proposed announced snapshot for milestone 1039245.
 
To make this snapshot as smooth, and as safe as possible, we have provided several scripts for the community to independently validate the snapshot and post the results here.
We suggest the community to do so in the upcoming hours. We are not stopping the network. IRI will roll back milestones to do the calculation. The more you wait the harder IRI will have to work.
 
# How to Validate
 
In order to validate this snapshot, we have provided a script for you to run and validate the Snapshot yourself.
 
Obviously, the main assumption is that you have a fully synced node up to 1039245 , and that you're at least a beginner developer.
 
1. Follow installation instuctions in: https://github.com/iotaledger/snapshot-validator
 
2. Run and Validate: Adjust validation script for your node host/port (Step 3. in `snapshot-validator`) and run with `npm start`
 
```var snapshotUrl = 'https://raw.githubusercontent.com/iotaledger/iri/release-v1.7.0/src/main/resources/snapshotMainnet.txt';``` ```var milestoneIndex = '1039245';```

3. Post your results as a comment below. (similar to #855)

### CODE REVIEW

**Comment by viossat** [comment]
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by HBMY289** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by IoTMOD** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by olazpreton** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by jakubcech** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by Masoholik** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by luca-moser** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by dterango** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by Ri5nV5** [comment]
> snapshot-validator@1.0.0 start /var/lib/iri/target/ixi/snapshot-validator
> node validate.js

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true
root@vmi204101:/var/lib/iri/target/ixi/snapshot-validator#

**Comment by pandamaci** [comment]
Node1:
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true

Node2:
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by lambtho12** [comment]
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by solareenlo** [comment]
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by ggreeve** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by no8ody** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by ahrain** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by maxi656** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by darwin4322** [comment]
image

**Comment by cyclux** [comment]
```BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true```

**Comment by ChrBender** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by VvanGemert** [comment]
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by HBMY289** [comment]
2nd node:
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by Hissi88** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by alon-e** [comment]
```json
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by mstx1** [comment]
BALANCE CORRECT: true
VALIDATING SNAPSHOT ENTRIES: 332122
LATEST STATE EQUALS SNAPSHOT: true
:+1:

**Comment by mettenian** [comment]
`BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true`

**Comment by hanspetzer** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by tctovsli** [comment]
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by f-ben** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by KiwiCat123** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by phschaeff** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  332122
LATEST STATE EQUALS SNAPSHOT:  true

**Pull request merged**
