### PR TITLE
Update snapshot to 08:00 UTC 20180709

### PR DESCRIPTION
**Pull request by th0br0**
This is the proposed announced snapshot for milestone 587745.

To make this snapshot as smooth, and as safe as possible, we have provided several scripts for the community to independently validate the snapshot and post the results here.
We suggest the community to do so before 2018/07/09 15:00 UTC, when the coordinator will restart and a new IRI version will be published.

# How to Validate

In order to validate this snapshot, we have provided a script for you to run and validate the Snapshot yourself.

Obviously, the main assumption is that you have a fully synced node with the latestSolidSubtangleMilestoneIndex at 587745 , and that you're at least a beginner developer.

1. Follow installation instuctions in: https://github.com/iotaledger/snapshot-validator

2. Run and Validate: Adjust validation script for your node host/port (Step 3. in `snapshot-validator`) and run with `npm start`

```var snapshotUrl = 'https://github.com/th0br0/iri/raw/418695db54573f4150ede33211fb19612c9f2c5f/src/main/resources/snapshotMainnet.txt';```

3. Post your results as a comment below. (similar to #735)

# What else will happen
- [x] Bump version to 1.5.1
- [x] Update list of addresses that were spent from
- [x] Update snapshot signature & signature indices
- [x] Update previousEchoSpentAddresses signature & signature index

### CODE REVIEW

**Comment by alon-e** [comment]
```javascript
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by Xermio** [comment]
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by maxi656** [comment]
Node1:

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by svenger87** [comment]
Node 1 
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true
```

Node 2 
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by HarmElaadNL** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by nuriel77** [comment]
```BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by maxi656** [comment]
Node2:
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

Node3:
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by luca-moser** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by michi6383** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by HenryWortel** [comment]
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by oyren** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by iota-cm** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by dterango** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by fijter** [comment]
```BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true```

**Comment by Alex6323** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by viossat** [comment]
All nodes agree with the snapshot:
```js
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by solareenlo** [comment]
BALANCE CORRECT: true
VALIDATING SNAPSHOT ENTRIES: 348252
LATEST STATE EQUALS SNAPSHOT: true

**Comment by schefei** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by schnico** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by NemesisFLX** [comment]
`BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true
`

**Comment by cym00n** [comment]
```BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true```

**Comment by gorcyka** [comment]
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by m-d-f** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by geminoz** [comment]
on quite a few nodes:

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by alexsporn** [comment]
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by tctovsli** [comment]
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by NetWalkerGit** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by iMarc0r** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by mettenian** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by didros** [comment]
Node 1
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

Node 2
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by maxi656** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by Johnny-Milkshakes** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by BaslerBebbi** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by MaKla89** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by curVV** [comment]
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  348252
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by Xilis** [comment]
BALANCE CORRECT: true
VALIDATING SNAPSHOT ENTRIES: 348252
LATEST STATE EQUALS SNAPSHOT: true

**Pull request merged**
