### PR TITLE
Feature: Doclet annotations

### LINKED ISSUE #1106: Add md-doclet as a dependency in IRI's pom.xml
### Description 
We need the md-doclet as a dependency in the pom.xml file.

### PR DESCRIPTION
**Pull request by kwek20**
# Description
Added doclet to dependencies
Added repo url as argument for doclet
Added Annotations at the methods we wish to document.
Modified some javadoc to work with the doclet. (no spaces in `<ul><li>, <p>`, etc)

Fixes #1106 
Fixes the IRI part of #1076.
The other half is work in progress: ledger/iri-mdx-doclet/issues/2

Reviewers can ignore every commit before `04df151`, this was merged, not rebased.

## Type of change
- Enhancement (a non-breaking change which adds functionality)
- Documentation Fix

# Checklist:
- [ ] My code follows the style guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

# Questions
Should we upload the doclet to JitPack, so that Travis can build the source?
Can we link to a JitPack source when specifiying `<docletArtifact>` inside a `<plugin>`?

### CODE REVIEW

**Comment by alon-e** [comment]
@kwek20 see Travis build - it can't fetch `com.iota:mdxdoclet:jar:0.2`
```
[ERROR] Failed to execute goal on project iri: Could not resolve dependencies for project com.iota:iri:jar:1.5.5: Could not find artifact com.iota:mdxdoclet:jar:0.2 in central (http://repo.maven.apache.org/maven2) -> [Help 1]
```

**Comment by kwek20** [comment]
@alon-e Yes i'm aware, see questions: "Should we upload the doclet to JitPack, so that Travis can build the source?"

**Comment by kwek20** [comment]
@alon-e @GalRogozinski 

Hmmmm, this still isnt fixed:
https://issues.apache.org/jira/browse/MJAVADOC-514

Havent gotten any of these solutions to work yet either.
https://stackoverflow.com/questions/35056526/maven-javadoc-plugin-overwrites-central-repository

**Comment by GalRogozinski** [comment]
It looks good. Opened issue #1432 after playing around a bit.
@jakubcech should also confirm whether the `mds` generated with `mvn site` are to his liking.

@kwek20 once buildkite is back up you just need to tell me which PR you want to merge first, this one or #1374

**Comment by jakubcech** [comment]
It's approved from my side. The issue was scoped to a specific definition and the site changed significantly since then. Jake and I will look at the layout and I'll create a subsequent issue if changes need to be made. This shouldn't be bloated up anymore.

**Comment by kwek20** [comment]
@GalRogozinski #1374 first please! Although its going to be a mess either way :D

**Pull request merged**
