### PR TITLE
Complete overhaul of Networking, Reporting, Threading

### PR DESCRIPTION
**Pull request by directorm**
**Complete overhaul of Networking, Reporting, and Threading.**

Reduced running threads by almost a 100 threads.

1. Made Non-Blocking incoming TCP replicator. The outgoing TCP is now push driven by Striped Executor tasks and properly connects/reconnects immediately handling typical errors.

2. Revised outgoing TCP and UDP for better control flow and error handling/recovery.

3. Moved a lot of threading (scheduled tasks etc.) into a Striped Executor for better control of thread allocation and purposes.

4. Revised Node.java to use Striped Executor for all request/reply/processing/broadcast tasks as well as enhanced queue management.

5. Created Non-blocking DNS Refresher - no more 30 second DNS refresh waits.

6. Separated out Neighbor management functions into a dedicated class - NeighborManager.java.

7. Made small changes wherever code was unclear.

8. Merged fixed Hash class as per recent github issues.

9. Introduced some locking in critical classes and cleaned up encapsulation.

10. Created functional interfaces and some useful utility classes.

Logging is a bit verbose - but left it in to show the new inner workings.
All tests passed.
Works very well. 

New package dirs: exec, scheduledReports, scheduledTasks, funcinterfaces, textutils - are all new. All old networking code cleaned out.

### CODE REVIEW

**Comment by th0br0** [comment]
Hey! Thanks for your large PR. I agree that a rewrite of the networking is required.

Do you perchance have a split-up version of your changes?
Also, what's your motivation for not using an established networking stack - e.g. netty?

At some point, I had time to start on rewriting everything using netty - but it's still missing some functionality: https://github.com/th0br0/iri/pull/1

**Comment by pompomJuice** [comment]
DRAMA

**Comment by th0br0** [comment]
This is not drama. A working solution is a working solution. Please stay on topic @pompomJuice

**Comment by directorm** [comment]
@th0br0 Got to put this on pause .... got a bug in the TCP neighboring ...  ARG ... DRATS.
I'll re-comment here as soon as I get it worked out ....
Netty sounds like an excellent solution. I'm just unfamiliar with it. Netty would cover the TCP NIO bit nicely I'd imagine.

The outbound needs to be NIO as well eventually. In the meantime this should work nicely.

**Comment by directorm** [comment]
Sorry guys - embarrassment is mine. Back to debugging. Everything works -- until it doesn't.

**Comment by directorm** [comment]
Testing is still in progress - please hold off until further notice.

**Pull request closed without merging**
