### PR TITLE
Feature: publish sn_trytes in zmq

### LINKED ISSUE #1550: sn_trytes, a custom zmq topic.
### Description

Creating `sn_trytes` topic that return complete trytes similar to tx_trytes but for `sn` transactions(confirmed) with the following streaming structure:
<<trytes, hash, milestone_index>>

Please note: I assume is possible at this stage to stream ordered bundle, so please keep that in mind.
 

### Motivation
- We need this for chronicle to keep it up to date with the tangle confirmed status.
- Streaming ordered bundles will force chronicle to reach eventual consistency on the tangle state.

### Requirements

- Ordered bundle stream(highly recommended).
- Complete sn trytes similar to tx_trytes structure with appended milestone_index at the end.

### Am I planning to do it myself with a PR?
No.

### PR DESCRIPTION
**Pull request by GalRogozinski**
# Description

Publishes confirmed transactions trytes to zmq with the following format

Fixes #1550 

## Type of change

- Enhancement (a non-breaking change which adds functionality)
- Documentation Fix

# How Has This Been Tested?

~TBD~
Tested manually

# Checklist:

_Please delete items that are not relevant._

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jakubcech** [comment]
@LouayKamel does this work for you?

**Comment by LouayKamel** [comment]
@jakubcech the code looks clean, so I suppose it does work, anyway will test it later today to confirm.

**Comment by jakubcech** [comment]
Did it work the way you need it to @LouayKamel ? Thanks :)

**Comment by DyrellC** [comment]
I was able to receive the `sn_trytes` when testing on my end

**Comment by jakubcech** [comment]
Can be merged. ✔️ by LK

**Comment by LouayKamel** [comment]
Thank you guys for your hard work!

**Comment by GalRogozinski** [comment]
@LouayKamel 
WilI finally merge it to next version
Are the bundles coming indeed in order?

**Comment by GalRogozinski** [comment]
Shouldn't be merged until documentation is ready

**Pull request merged**
