### PR TITLE
Change: Curl improvement

### PR DESCRIPTION
**Pull request by muXxer**
# Description

powsrv.io Team optimized the curl transform formulas.
On my machine it's around 7% faster than before in golang and in C.
Didn't benchmark the improvement in Java :)

## Type of change

- Enhancement (a non-breaking change which adds functionality)

# How Has This Been Tested?

- PearlDiverTest.java
- CurlTest.java

# Checklist:

- [X] My code follows the style guidelines for this project
- [X] I have performed a self-review of my own code
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by nmeylan** [comment]
Hello muxxer, I was curious about your PR so I ran a quick Benchmark of these changes on my laptop (cpu 2,3 GHz Intel Core i7)
```java
package com.iota.iri.crypto;

import com.iota.iri.utils.Converter;
import com.iota.iri.utils.Pair;
import org.junit.Test;
import org.openjdk.jmh.annotations.*;
import org.openjdk.jmh.runner.Runner;
import org.openjdk.jmh.runner.RunnerException;
import org.openjdk.jmh.runner.options.Options;
import org.openjdk.jmh.runner.options.OptionsBuilder;

import java.util.Random;
import java.util.concurrent.TimeUnit;

public class CurlBenchmark {

  private static Random seed = new Random();
  private static String trytes = "RSWWSFXPQJUBJROQBRQZWZXZJWMUBVIVMHPPTYSNW9YQIQQF9RCSJJCVZG9ZWITXNCSBBDHEEKDRBHVTWCZ9SZOOZHVBPCQNPKTWFNZAWGCZ9QDIMKRVINMIRZBPKRKQAIPGOHBTHTGYXTBJLSURDSPEOJ9UKJECUKCCPVIQQHDUYKVKISCEIEGVOQWRBAYXWGSJUTEVG9RPQLPTKYCRAJ9YNCUMDVDYDQCKRJOAPXCSUDAJGETALJINHEVNAARIPONBWXUOQUFGNOCUSSLYWKOZMZUKLNITZIFXFWQAYVJCVMDTRSHORGNSTKX9Z9DLWNHZSMNOYTU9AUCGYBVIITEPEKIXBCOFCMQPBGXYJKSHPXNUKFTXIJVYRFILAVXEWTUICZCYYPCEHNTK9SLGVL9RLAMYTAEPONCBHDXSEQZOXO9XCFUCPPMKEBR9IEJGQOPPILHFXHMIULJYXZJASQEGCQDVYFOM9ETXAGVMSCHHQLFPATWOSMZIDL9AHMSDCE9UENACG9OVFAEIPPQYBCLXDMXXA9UBJFQQBCYKETPNKHNOUKCSSYLWZDLKUARXNVKKKHNRBVSTVKQCZL9RY9BDTDTPUTFUBGRMSTOTXLWUHDMSGYRDSZLIPGQXIDMNCNBOAOI9WFUCXSRLJFIVTIPIAZUK9EDUJJ9B9YCJEZQQELLHVCWDNRH9FUXDGZRGOVXGOKORTCQQA9JXNROLETYCNLRMBGXBL9DQKMOAZCBJGWLNJLGRSTYBKLGFVRUF9QOPZVQFGMDJA9TBVGFJDBAHEVOLW9GNU9NICLCQJBOAJBAHHBZJGOFUCQMBGYQLCWNKSZPPBQMSJTJLM9GXOZHTNDLGIRCSIJAZTENQVQDHFSOQM9WVNWQQJNOPZMEISSCLOADMRNWALBBSLSWNCTOSNHNLWZBVCFIOGFPCPRKQSRGKFXGTWUSCPZSKQNLQJGKDLOXSBJMEHQPDZGSENUKWAHRNONDTBLHNAKGLOMCFYRCGMDOVANPFHMQRFCZIQHCGVORJJNYMTORDKPJPLA9LWAKAWXLIFEVLKHRKCDG9QPQCPGVKIVBENQJTJGZKFTNZHIMQISVBNLHAYSSVJKTIELGTETKPVRQXNAPWOBGQGFRMMK9UQDWJHSQMYQQTCBMVQKUVGJEAGTEQDN9TCRRAZHDPSPIYVNKPGJSJZASZQBM9WXEDWGAOQPPZFLAMZLEZGXPYSOJRWL9ZH9NOJTUKXNTCRRDO9GKULXBAVDRIZBOKJYVJUSHIX9F9O9ACYCAHUKBIEPVZWVJAJGSDQNZNWLIWVSKFJUMOYDMVUFLUXT9CEQEVRFBJVPCTJQCORM9JHLYFSMUVMFDXZFNCUFZZIKREIUIHUSHRPPOUKGFKWX9COXBAZMQBBFRFIBGEAVKBWKNTBMLPHLOUYOXPIQIZQWGOVUWQABTJT9ZZPNBABQFYRCQLXDHDEX9PULVTCQLWPTJLRSVZQEEYVBVY9KCNEZXQLEGADSTJBYOXEVGVTUFKNCNWMEDKDUMTKCMRPGKDCCBDHDVVSMPOPUBZOMZTXJSQNVVGXNPPBVSBL9WWXWQNMHRMQFEQYKWNCSW9URI9FYPT9UZMAFMMGUKFYTWPCQKVJ9DIHRJFMXRZUGI9TMTFUQHGXNBITDSORZORQIAMKY9VRYKLEHNRNFSEFBHF9KXIQAEZEJNQOENJVMWLMHI9GNZPXYUIFAJIVCLAGKUZIKTJKGNQVTXJORWIQDHUPBBPPYOUPFAABBVMMYATXERQHPECDVYGWDGXFJKOMOBXKRZD9MCQ9LGDGGGMYGUAFGMQTUHZOAPLKPNPCIKUNEMQIZOCM9COAOMZSJ9GVWZBZYXMCNALENZ9PRYMHENPWGKX9ULUIGJUJRKFJPBTTHCRZQKEAHT9DC9GSWQEGDTZFHACZMLFYDVOWZADBNMEM9XXEOMHCNJMDSUAJRQTBUWKJF9RZHK9ACGUNI9URFIHLXBXCEODONPXBSCWP9WNAEYNALKQHGULUQGAFL9LB9NBLLCACLQFGQMXRHGBTMI9YKAJKVELRWWKJAPKMSYMJTDYMZ9PJEEYIRXRMMFLRSFSHIXUL9NEJABLRUGHJFL9RASMSKOI9VCFRZ9GWTMODUUESIJBHWWHZYCLDENBFSJQPIOYC9MBGOOXSWEMLVU9L9WJXKZKVDBDMFSVHHISSSNILUMWULMVMESQUIHDGBDXROXGH9MTNFSLWJZRAPOKKRGXAAQBFPYPAAXLSTMNSNDTTJQSDQORNJS9BBGQ9KQJZYPAQ9JYQZJ9B9KQDAXUACZWRUNGMBOQLQZUHFNCKVQGORRZGAHES9PWJUKZWUJSBMNZFILBNBQQKLXITCTQDDBV9UDAOQOUPWMXTXWFWVMCXIXLRMRWMAYYQJPCEAAOFEOGZQMEDAGYGCTKUJBS9AGEXJAFHWWDZRYEN9DN9HVCMLFURISLYSWKXHJKXMHUWZXUQARMYPGKRKQMHVR9JEYXJRPNZINYNCGZHHUNHBAIJHLYZIZGGIDFWVNXZQADLEDJFTIUTQWCQSX9QNGUZXGXJYUUTFSZPQKXBA9DFRQRLTLUJENKESDGTZRGRSLTNYTITXRXRGVLWBTEWPJXZYLGHLQBAVYVOSABIVTQYQM9FIQKCBRRUEMVVTMERLWOK";
  private static String hash = "TIXEPIEYMGURTQ9ABVYVQSWMNGCVQFASMFAEQWUZCLIWLCDIGYVXOEJBBEMZOIHAYSUQMEFOGZBXUMHQW";

  @Test
  public void launchCurlBenchmark() throws RunnerException {
    Options opts = new OptionsBuilder()
      .include(CurlBenchmark.class.getSimpleName())
      .mode(Mode.AverageTime)
      .timeUnit(TimeUnit.MILLISECONDS)
      .warmupIterations(5)
      .forks(1)
      .measurementIterations(10)
      .shouldFailOnError(true)
      .shouldDoGC(false)
      .build();
    new Runner(opts).run();
  }
  @Benchmark
  @BenchmarkMode(Mode.AverageTime) @OutputTimeUnit(TimeUnit.MICROSECONDS)
  public void test() {
    pairHashWorks();
  }

  public void pairHashWorks() {
    int size = 8019;
    byte[] in_trits = new byte[size];
    Converter.trits(trytes, in_trits, 0);
    Pair<long[], long[]> hashPair = new Pair<>(new long[Curl.HASH_LENGTH], new long[Curl.HASH_LENGTH]);
    Curl curl;
    curl = new Curl(true, SpongeFactory.Mode.CURLP81);
    curl.absorb(Converter.longPair(in_trits), 0, in_trits.length);
    curl.squeeze(hashPair, 0, Curl.HASH_LENGTH);
  }
}
```

Here the results

## Without this PR
```
# JMH version: 1.21
# VM version: JDK 1.8.0_144, Java HotSpot(TM) 64-Bit Server VM, 25.144-b01
# VM invoker: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/bin/java
# Warmup: 5 iterations, 10 s each
# Measurement: 10 iterations, 10 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Average time, time/op
# Benchmark: com.iota.iri.crypto.CurlBenchmark.test

# Run progress: 0.00% complete, ETA 00:02:30
# Fork: 1 of 1
# Warmup Iteration   1: 5.272 ms/op
# Warmup Iteration   2: 5.499 ms/op
# Warmup Iteration   3: 5.549 ms/op
# Warmup Iteration   4: 5.509 ms/op
# Warmup Iteration   5: 5.514 ms/op
Iteration   1: 5.606 ms/op
Iteration   2: 5.476 ms/op
Iteration   3: 5.476 ms/op
Iteration   4: 5.396 ms/op
Iteration   5: 5.414 ms/op
Iteration   6: 5.439 ms/op
Iteration   7: 5.481 ms/op
Iteration   8: 5.375 ms/op
Iteration   9: 5.417 ms/op
Iteration  10: 5.402 ms/op

Result "com.iota.iri.crypto.CurlBenchmark.test":
  5.448 ±(99.9%) 0.101 ms/op [Average]
  (min, avg, max) = (5.375, 5.448, 5.606), stdev = 0.067
  CI (99.9%): [5.347, 5.549] (assumes normal distribution)
```

## With this PR
```
# JMH version: 1.21
# VM version: JDK 1.8.0_144, Java HotSpot(TM) 64-Bit Server VM, 25.144-b01
# VM invoker: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/bin/java
# Warmup: 5 iterations, 10 s each
# Measurement: 10 iterations, 10 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Average time, time/op
# Benchmark: com.iota.iri.crypto.CurlBenchmark.test

# Run progress: 0.00% complete, ETA 00:02:30
# Fork: 1 of 1
# Warmup Iteration   1: 7.863 ms/op
# Warmup Iteration   2: 9.553 ms/op
# Warmup Iteration   3: 9.608 ms/op
# Warmup Iteration   4: 9.746 ms/op
# Warmup Iteration   5: 9.733 ms/op
Iteration   1: 7.206 ms/op
Iteration   2: 7.043 ms/op
Iteration   3: 7.040 ms/op
Iteration   4: 7.017 ms/op
Iteration   5: 7.210 ms/op
Iteration   6: 7.160 ms/op
Iteration   7: 7.110 ms/op
Iteration   8: 7.049 ms/op
Iteration   9: 7.109 ms/op
Iteration  10: 7.099 ms/op

Result "com.iota.iri.crypto.CurlBenchmark.test":
  7.104 ±(99.9%) 0.105 ms/op [Average]
  (min, avg, max) = (7.017, 7.104, 7.210), stdev = 0.069
  CI (99.9%): [7.000, 7.209] (assumes normal distribution)
```

**Comment by GalRogozinski** [comment]
@nmeylan 
Did you run the test in a clean slate where nothing runs in the background?
The results are not very encouraging :-(

By the way the benchmark code itself lgtm :-)
If you want you can PR it. We have a benchmarks folder in IRI.
Just please add a new line above `@Benchmark` and make `pairHashWorks` private (not so important it just hurts my eyes)

**Comment by nmeylan** [comment]
@GalRogozinski 
Unfortunately, I didn't run this test in an isolated environment, but both executions ran in same condition.

I've also edited my comment to use **Throughput** instead of **Average Time** which gives clearer results.

**Comment by GalRogozinski** [comment]
Hmm I see now the PR has higher throughput which is good.
But before your edit it had a higher average time which wasn't good.

Anyhows, it is best to add another comment instead of editing existing comments so that others would know what were the former results.

If you PR your benchmark I will run it before the 1.6.2 release (but after 1.6.1 will be released)

**Comment by nmeylan** [comment]
Ah you may have seen my very first comment where the average time were greater, I made a mistake that I quickly fix, so forget it. (that's why I edited it)

I will PR to add benchmark

**Comment by muXxer** [comment]
@nmeylan thank you very much for the benchmarks. Good work 👌

**Comment by GalRogozinski** [comment]
The improvement in this PR is based on the Quine-Mccluskey algorithm

It is important to note that this PR changes the pair-wise hashing code which is not currently used in IRI, so merging it won't have any effect

**Comment by alon-e** [comment]
@Wollac - this is the Curl improv. we talked about you reviewing ^. :)

**Comment by Wollac** [comment]
@alon-e 
Oh, I already reviewed more or less the same changes in [entangled](https://github.com/iotaledger/entangled/pull/803#pullrequestreview-204522071).
What do you think is this enough? Or what do we want to do for iri?

**Comment by muXxer** [comment]
@Wollac @alon-e 
I added the changes wollac suggested.
 https://github.com/iotaledger/entangled/pull/803#pullrequestreview-204522071

**Pull request merged**
