### PR TITLE
Project-wide fix needed - InterruptExceptions ignored and not reset

### PR DESCRIPTION
**Pull request by footloosejava**
… sleeps, waits, and joins (and interrupts from blocking IO operations) need to be attended instead of ignored, and the thread Interrupt status needs to be reset to prevent further blockages.

Unless the interrupt is accidental (99% never the case), then all InterruptedExceptions need to be handled by resetting the interrupt status and then issuing a break/return/shutdown.

If this is not done, than any further blocking operations will continue to block and never return.
If an operation is 'shutdown' and may be in a blocking state, then a 'shutdown' flag change should also be accompanied by 'Thread.currentThread().interrupt();'

Reference: https://www.javaspecialists.eu/archive/Issue056.html

)

```
try {
   blocking op that can throw interruptExceptionm
} catch (final InterruptedException e) {
   Thread.currentThread().interrupt();
   (break or return or whatever)
}
```

### CODE REVIEW

**Comment by footloosejava** [comment]
@GalRogozinski  Feel free to close this if this is something that will be done in a project-wide refactoring. It involves pretty much every time a sleep, join, wait or other Interruption is thrown. A lot of classes will need a minor edit to bring this up to spec.

**Comment by GalRogozinski** [comment]
The main reason this was not tended to is because of the size (again).
If you will break this up to formatting PR and PR with changes I will look at it.

**Comment by GalRogozinski** [comment]
Just wondering @footloosejava,
will you do a new PR?

**Comment by footloosejava** [comment]
No.

**Comment by GalRogozinski** [comment]
@footloosejava, I Saw your other comments that you are busy with other work only after I answered.
Good luck!

**Comment by footloosejava** [comment]
Thanks!

**Comment by GalRogozinski** [comment]
Since there are many conflicts and the PR is too large, it is better to redo this.
See #1583

**Pull request closed without merging**
