### PR TITLE
Enhancement: Add endpoint to return IRI's api configuration

### LINKED ISSUE #496: Enable apps to discover request size limits programmatically
The IRI enforces certain configurable limits on requests (e.g., [`maxRequestList`](https://github.com/iotaledger/iri/blob/v1.4.1.6/src/main/java/com/iota/iri/service/API.java#L111)).

Applications can (respecfully) work around these limits by "chunking" large requests into several smaller ones.

However, currently the applications developer has to configure these limits manually to match the IRI configuration.

It would be a nice QoL enhancement if there were a way for an application to get these limits programmatically (e.g., from a `getNodeInfo` response), so that it can auto-configure its request chunking.

### PR DESCRIPTION
**Pull request by nmeylan**
# Description

Add a new endpoint "getApiConfiguration" returns the configuration of the
IRI's api

Fixes #496

# How Has This Been Tested?

Integration test.

# Checklist:

_Please delete items that are not relevant._

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by GalRogozinski** [comment]
@nmeylan 
Soon there will be a new configuration infrastructure.
After it will be completed we will have interfaces like `ApiConfiguration` and `TipSelectionConfiguration`.
Then one could create your feature via reflection. Meaning if we add configuration parameters they will automatically be added to your Api call.

Will you be interested in implementing your feature under the new configuration design once it is available?

**Comment by nmeylan** [comment]
Hello Gal, yes I would be interested to implement this api based on the new configuration implementation :)

**Comment by GalRogozinski** [comment]
@nmeylan as soon as the new code is merged we will be in touch :)

**Comment by jakubcech** [comment]
Hi @nmeylan , we have merged the configuration rework (https://github.com/iotaledger/iri/pull/910)  so the new interfaces are now available. Would you be willing to give it a stab using the new approach now?

**Comment by nmeylan** [comment]
Hi @jakubcech, I would be interested to implement that but currently I don't have the time 😞 
Maybe someone else would be interested as well. If yes, you can just close this pull request 😄

**Comment by jakubcech** [comment]
Thanks for getting back to us @nmeylan . I'll create a new issue and reference this PR in it. Cheers :)

**Pull request closed without merging**
