### PR TITLE
Update snapshot to 16:00 UTC 20180128

### PR DESCRIPTION
**Pull request by th0br0**
This is the proposed announced snapshot for milestone 337541.

To make this snapshot as smooth, and as safe as possible, we have provided several scripts for the community to independently validate the snapshot and post the results here.
We suggest the community to do so before 20180128 23:00 UTC, when the coordinator and a new IRI version will be published.

# How to Validate
In order to validate this snapshot, we have provided a script for you to run and validate the Snapshot yourself. Obviously, the main assumption is that you have a fully synced node with the latestSolidSubtangleMilestoneIndex at 337541 , and that you're at least a beginner developer.

1. *Get IXI*: Download the IXI module from https://github.com/iotaledger/Snapshot.ixi and place it in your IXI folder. (easiest way is to do: `git clone https://github.com/iotaledger/Snapshot.ixi Snapshot` in your ixi folder - make sure that the folder is called `Snapshot`!).
2. *Get Validation Script*: https://gist.github.com/th0br0/8b92cfe79b89979c67efdc418ff55860 and run `npm i request`
3. *Run and Validate*: Adjust validation script for your node host/port and run with `node 20180128-validation.js` and then post your results.

### CODE REVIEW

**Comment by th0br0** [comment]
The Travis CI build will be fixed (issue is caused by not-updated signature) once verification has happened.

**Comment by olaf-2** [comment]
Node iota.apocha.net
`
BALANCE CORRECT:  true

VALIDATING SNAPSHOT ENTRIES:  260629

LATEST STATE EQUALS SNAPSHOT:  true
`

**Comment by scorpionofwar** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by Xermio** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by chrisoro** [comment]
3 nodes, all:

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by luca-moser** [comment]
1 node:

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by jordansteeves** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by Tyrix** [comment]
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by CWarner818** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by maxi656** [comment]
1 (node02.nodeblie.de)

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by cyclux** [comment]
```BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true```

**Comment by svenger87** [comment]
Node #1:
`BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true`

Node #2:
`BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true`

**Comment by ralfr** [comment]
nodes.iota.fm / Node 1:

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by Makerpopo** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by OMSKremer** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by ralfr** [comment]
nodes.ioda.fm / Node 2:

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by nuriel77** [comment]
```sh
# node 20180128-validation.js
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by ralfr** [comment]
nodes.iota.fm / Node 3:

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by maxi656** [comment]
2 (node03.nodeblie.de)

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by ds2216** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by rajivshah3** [comment]
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by rckey** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by terrordaddy** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by Leibi133** [comment]
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by marimes** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by ralfr** [comment]
nodes.iota.fm / Node 4:

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by maxi656** [comment]
3 (node04.nodeblie.de)

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by 0xNeffarion** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by pokenprod** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by maxi656** [comment]
4 (node01.nodeblie.de)

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by georgmittendorfer** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by ralfr** [comment]
nodes.iota.fm / Trinity Node

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by ralfr** [comment]
nodes.iota.fm / Nelson Node

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by ralfr** [comment]
nodes.iota.fm / 6 more private (corporate) nodes 

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by IoTMOD** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by brunoamancio** [comment]
iota.love

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by KeenHero** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by Niuran78** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by egdels** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by tictyc** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by markschwed** [comment]
xxx@IOTA:/home/iota/node/ixi/Snapshot$ sudo node 20180128-validation.js
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by Rachdingue** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by maxmbed** [comment]
Can't make it work :( : 
COULD NOT PROCESS REQUEST! { Error: connect ECONNREFUSED 127.0.0.1:14265
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1207:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 14265 }

**Comment by Donk119** [comment]
BALANCE CORRECT: true
VALIDATING SNAPSHOT ENTRIES: 260629
LATEST STATE EQUALS SNAPSHOT: true

**Comment by stein1** [comment]
two nodes, same result:

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by creps** [comment]
Snapshot# node 20180128-validation.js 
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by Citrullin** [comment]
Needed to restart after cloning the ixi scripts (https://github.com/iotaledger/Snapshot.ixi)
Created a issue for it (https://github.com/iotaledger/Snapshot.ixi/issues/6)

The end result:
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by Citrullin** [comment]
@maxmbed What was the result of the first step? (this call: curl http://localhost:14265 -X POST -H 'X-IOTA-API-Version: 1.4.1' -H 'Content-Type: application/json'   -d '{"command": "Snapshot.getState"}') Many transaction hashes? Did you try to restart the node after cloning the ixi scripts? Can you execute the following and post the result? 
```
curl http://localhost:14265 -X POST -H 'Content-Type: application/json' -H 'X-IOTA-API-Version: 1.4' -d '{"command": "getNodeInfo"}' | jq
```

**Comment by curVV** [comment]
```
BALANCE CORRECT:  true  
VALIDATING SNAPSHOT ENTRIES:  260629  
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by cym00n** [comment]
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by dwjorgeb** [comment]
Am I the only one with the node stuck @ Milestone 337268?

"latestMilestone": "PNXQSZNOJCRVXMFHRLJOZWYKLBACNHCU9JQTRRMFSN9JZIOMVJWAFPSQHJHZEAZGVMNQGOIFUSJUZ9999",
  "latestMilestoneIndex": 337268,
  "latestSolidSubtangleMilestone": "PNXQSZNOJCRVXMFHRLJOZWYKLBACNHCU9JQTRRMFSN9JZIOMVJWAFPSQHJHZEAZGVMNQGOIFUSJUZ9999",
  "latestSolidSubtangleMilestoneIndex": 337268,

**Comment by rdudley** [comment]
/home/iota/node/ixi/Snapshot# node 20180128-validation.js
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by pandamaci** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by tctovsli** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by nuttycoins** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by Citrullin** [comment]
@dwjorgeb You're node is not up to date. I think it's because of not enough enough neighbors. Or they are not connected to the tangle. 
The latest milestone is 337541 not 337268. But it's crazy that you didn't get the newest milestone by the coordinator. I would suggest to stop the node, remove the database and download the latest database:
```
cd /tmp/ && curl -LO http://db.iota.partners/IOTA.partners-mainnetdb.tar.gz && sudo -u iota tar xzfv /tmp/IOTA.partners-mainnetdb.tar.gz -C /home/iota/node/mainnetdb && rm /tmp/IOTA.partners-mainnetdb.tar.gz
```
(source: http://iota.partners/)
Restart the node and you should be on latest milestone. You can then continue with the snapshot process. I highly recommend to use Nelson. ;) https://github.com/SemkoDev/nelson.cli

**Comment by maxmbed** [comment]
> @maxmbed What was the result of the first step? (this call: curl http://localhost:14265 -X POST -H 'X-IOTA-API-Version: 1.4.1' -H 'Content-Type: application/json' -d '{"command": "Snapshot.getState"}') Many transaction hashes? Did you try to restart the node after cloning the ixi scripts? Can you execute the following and post the result?

@Citrullin yes, I restarted IRI just after cloning IXI. But still no success. 

The ouput your command give : 

`{
  "appName": "IRI",
  "appVersion": "1.4.1.7",
  "jreAvailableProcessors": 2,
  "jreFreeMemory": 1773110504,
  "jreVersion": "1.8.0_151",
  "jreMaxMemory": 5726797824,
  "jreTotalMemory": 2545418240,
  "latestMilestone": "KINNCJGTUCYAGCMSEGLYS9KMQDIBRZQZRESHFHRRGVBBPHAWWEURMYVHR9JYJFYWQM9TADCQLJXPZ9999",
  "latestMilestoneIndex": 337541,
  "latestSolidSubtangleMilestone": "KINNCJGTUCYAGCMSEGLYS9KMQDIBRZQZRESHFHRRGVBBPHAWWEURMYVHR9JYJFYWQM9TADCQLJXPZ9999",
  "latestSolidSubtangleMilestoneIndex": 337541,
  "neighbors": 5,
  "packetsQueueSize": 0,
  "time": 1517162912656,
  "tips": 21,
  "transactionsToRequest": 0,
  "duration": 1
}`

**Comment by Roeland54** [comment]
1 node :
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by maxmbed** [comment]
My bad the correspond output of Snapshot.getState is : 

`{
  "error": "Command [Snapshot.getState] is unknown",
  "duration": 1
}
`

**Comment by Citrullin** [comment]
@maxmbed Can you please not use the inline code highlighting. Here's a nice markdown cheat sheet: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

Better use this one
````
```
No language indicated, so no syntax highlighting. 
But let's throw in a <b>tag</b>.
```
````

It's more readable :)

**Comment by Citrullin** [comment]
@maxmbed Let's continues this in the following issue: https://github.com/iotaledger/Snapshot.ixi/issues/6 Seems to be related. :)

**Comment by chroonag** [comment]
looks good:

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by dwjorgeb** [comment]
@Citrullin I'm using Nelson to manage my neighbours.

I rebooted and ran IRI with --revalidate tag, let's see how it goes.

**Comment by dterango** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by pandamaci** [comment]
Other node:

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by shrewm** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by hans0r** [comment]
nodes of hans0r.. all
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by schnico** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by sayravai** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by iotadance** [comment]
BALANCE CORRECT: true
VALIDATING SNAPSHOT ENTRIES: 260629
LATEST STATE EQUALS SNAPSHOT: true

**Comment by mettenian** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by lunfardo314** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

from http://node.iotalt.com:14600

**Comment by joekhondius** [comment]
My node fell out of sync some days ago.
The validation fails
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
FATAL ERROR: Balance incorrect for:  99BNX9QCBXLDXIKWWGVPWYMPKCQGPAATDE9NOSNVABIZHBRJHUYMPIYHHGODPYCNGUHIYVCZQCBFYWVCA
Balance (proposed snapshot vs. local):  310000000 NaN
FATAL ERROR: Balance incorrect for:  99BZLTCIBHCIM9DONME9YERVQZVUXUDTZNNVJWMJTSJP9E9WBIZIVNPBOTFXMCPLBBVTUJR9K9UHQNDHD

etc etc

**Comment by joekhondius** [comment]
to be expected i guess?
iri 1.4.1.7 
latestMilestoneIndex":337541
latestSolidSubtangleMilestoneIndex":337230

**Comment by valshare** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by maxmbed** [comment]
Solve. It was a dumb path issue. If you had the same problem, please check if ixi path is /home/iota/node/ixi

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by Logikgate** [comment]
All good
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by darrenolson** [comment]
@green_protocol Node 1:
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by stockermans** [comment]
```
BALANCE CORRECT: true
VALIDATING SNAPSHOT ENTRIES: 260629
LATEST STATE EQUALS SNAPSHOT: true
```

**Comment by malfidev** [comment]
@Malfi node:
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by darrenolson** [comment]
@green_protocol Node 2: 
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by darrenolson** [comment]
@green_protocol Node 3: 
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by darrenolson** [comment]
@green_protocol Node 4:
BALANCE CORRECT: true
VALIDATING SNAPSHOT ENTRIES: 260629
LATEST STATE EQUALS SNAPSHOT: true

**Comment by darrenolson** [comment]
@green_protocol Node 5:
BALANCE CORRECT: true
VALIDATING SNAPSHOT ENTRIES: 260629
LATEST STATE EQUALS SNAPSHOT: true

**Comment by michi6383** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by chrootLogin** [comment]
```
# node 20180128-validation.js
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by feux0r** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by darrenolson** [comment]
@green_protocol Node 6:
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by darrenolson** [comment]
@green_protocol Node 7:
BALANCE CORRECT: true
VALIDATING SNAPSHOT ENTRIES: 260629
LATEST STATE EQUALS SNAPSHOT: true

**Comment by darrenolson** [comment]
@green_protocol Node 8:
BALANCE CORRECT: true
VALIDATING SNAPSHOT ENTRIES: 260629
LATEST STATE EQUALS SNAPSHOT: true

**Comment by devlaam** [comment]
$ node 20180128-validation.js
COULD NOT PROCESS REQUEST! null
$  curl http://localhost:15625  -X POST -H 'X-IOTA-API-Version: 1.4.1' -H 'Content-Type: application/json'   -d '{"command": "getNodeInfo"}'
{"appName":"IRI","appVersion":"1.4.1.7","jreAvailableProcessors":4,"jreFreeMemory":777283320,"jreVersion":"1.8.0_151","jreMaxMemory":1994391552,"jreTotalMemory":1994391552,"latestMilestone":"KINNCJGTUCYAGCMSEGLYS9KMQDIBRZQZRESHFHRRGVBBPHAWWEURMYVHR9JYJFYWQM9TADCQLJXPZ9999","latestMilestoneIndex":337541,"latestSolidSubtangleMilestone":"KINNCJGTUCYAGCMSEGLYS9KMQDIBRZQZRESHFHRRGVBBPHAWWEURMYVHR9JYJFYWQM9TADCQLJXPZ9999","latestSolidSubtangleMilestoneIndex":337541,"neighbors":8,"packetsQueueSize":0,"time":1517170884465,"tips":711,"transactionsToRequest":0,"duration":0}

**Comment by Antyrael** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by akomelj** [comment]
On both my nodes OK:

```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by Johnny-Milkshakes** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by seppeg2** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by Citrullin** [comment]
@joekhondius shut down your node. Download the newest DB and restart the node:
```
cd /tmp/ && curl -LO http://db.iota.partners/IOTA.partners-mainnetdb.tar.gz && sudo -u iota tar xzfv /tmp/IOTA.partners-mainnetdb.tar.gz -C /home/iota/node/mainnetdb && rm /tmp/IOTA.partners-mainnetdb.tar.gz
```
Source: http://iota.partners/

**Comment by Citrullin** [comment]
@devlaam What was the output of:
```
curl http://localhost:14265 -X POST -H 'X-IOTA-API-Version: 1.4.1' -H 'Content-Type: application/json'   -d '{"command": "Snapshot.getState"}'
```

If it was:
```
{ "error": "Command [Snapshot.getState] is unknown", "duration": 1 }
```
just take a look into: https://github.com/iotaledger/Snapshot.ixi/issues/6

**Comment by ManMs** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by Citrullin** [comment]
@dwjorgeb That's a crazy behavior. Do you also have static neighbors or only nelson neighbors? Maybe you should dig into this deeper if it repeats. You just should out of sync with the tangle.

**Comment by squa99** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by philb74** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by NetWalkerGit** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by GeloVidal** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by stockermans** [comment]
@devlaam restart iri, and once you see in the iri output that it loaded the Snapshot ixi module, then launch the "node 20180128-validation.js"

**Comment by jessekerkhoven** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by vanbak** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by yippykaiyay012** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by House-Atreides** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by manuelbieh** [comment]
BALANCE CORRECT:  true                                        VALIDATING SNAPSHOT ENTRIES:  260629                          LATEST STATE EQUALS SNAPSHOT:  true

**Comment by geminoz** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by ignitenz** [comment]
BALANCE CORRECT: true
VALIDATING SNAPSHOT ENTRIES: 260629
LATEST STATE EQUALS SNAPSHOT: true

On both of my nodes.

**Comment by th0br0** [comment]
Thanks everyone for verifying!

**Comment by tawago** [comment]
two nodes 
```bash
$ node 20180128-validation.js                           
BALANCE CORRECT:  true                                  
VALIDATING SNAPSHOT ENTRIES:  260629                    
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by B4sti3n** [comment]
BALANCE CORRECT: true
VALIDATING SNAPSHOT ENTRIES: 260629
LATEST STATE EQUALS SNAPSHOT: true

**Pull request merged**
