### PR TITLE
print out line number in log info.

### LINKED ISSUE #1361: print out line number in log info
### Description
print out line number in log info 

### Motivation
be convenient to debugging

### Requirements
output the line number of every log info.

### Open Questions (optional)
Anything you want to discuss.

### Am I planning to do it myself with a PR?
Yes.

### PR DESCRIPTION
**Pull request by lhfbc**
# Description

print out the line number in log info. It will be convenient for debugging.

For example, the output will be changed from

02/26 19:25:04.039 [main] INFO  com.iota.iri.IRI$IRILauncher - Welcome to IRI Testnet 1.6.1-RELEASE

to

02/26 19:25:04.039 [main] INFO  com.iota.iri.IRI$IRILauncher:117 - Welcome to IRI Testnet 1.6.1-RELEASE

Fixes  #1361

## Type of change

- Enhancement (a non-breaking change which adds functionality)

# How Has This Been Tested?

compare the log output between before and after modification.

# Checklist:

- [ ] My code follows the style guidelines for this project
- [ ] I have performed a self-review of my own code

### CODE REVIEW

**Comment by GalRogozinski** [comment]
I think it makes the log a bit ugly, but maybe others will disagree.
@kwek20 what do you think?

**Comment by lhfbc** [comment]
> I think it makes the log a bit ugly, but maybe others will disagree.
> @kwek20 what do you think?

In the future, if the number of code in IOTA is growing really fast, and there are distributed deployment, without the line number, it will be really inefficient to triage bugs. That's my opinion.

**Comment by th0br0** [comment]
You could truncate the classname given the common prefix (`com.iota.iri` => `iri`) which would reduce the impact of this. Given the rather long files we have occasionally this might make sense?

**Comment by GalRogozinski** [comment]
I agree with @th0br0 
@lhfbc wants to do it?

**Comment by lhfbc** [comment]
> I agree with @th0br0
> @lhfbc wants to do it?

Yes.
I have 2 options:
"02/27 17:36:13.670 [main] INFO  IRI.java:117 - Welcome to IRI Testnet 1.6.1-RELEASE"
or 
"02/27 17:29:49.463 [main] INFO  IRI$IRILauncher:117 - Welcome to IRI Testnet 1.6.1-RELEASE"

The first will be the file name, but every file will have a suffix ".java".
And the second will be the class name, where 'IRILauncher' is a private class in 'IRI', with '$' splitting them.

Which one will be better?

**Comment by GalRogozinski** [comment]
Definitely the second one

**Comment by legacycode** [comment]
👍 for the second one. I like the line numbers.

**Comment by lhfbc** [comment]
Hello, @GalRogozinski  @legacycode @th0br0, would you please review the code?

**Comment by lhfbc** [comment]
@GalRogozinski @kwek20 @legacycode  @th0br0, would anyone of you like to merge it? This pr has been lasting for many days ... :)

**Pull request merged**
