### PR TITLE
Linked blocking queue

### LINKED ISSUE #1742: Error while shuting down IRI
### Bug description
While shutting down IRI errors were thrown and it is unclear whether all data was properly saved to db...
The `hs_err_pid1.log` wasn't created because I had a fromer log that I didn't delete on my machine.
If the problem will be recreated the contents of the file will be uploaded in a comment

### IRI version
`iotacafe/iri-dev:c9c74c2-e5c639c8` this is the commit that is supposed to spawn off the 1.9.0 branch

### Hardware Spec
Hetzner CX51

### Steps To Reproduce
1.  Sync nodes from a not too recent snapshot
2. Wait for syncing to be stuck
3. Shut down IRI

### Expected behaviour
No errors
### Actual behaviour
Errors

### Errors
```
02/04 14:01:49.721 [Local Snapshots Monitor] INFO  ThreadUtils:78 - Local Snapshots Monitor [STOPPED]
02/04 14:01:49.726 [pool-12-thread-3] INFO  TransactionProcessingPipelineImpl:158 - validation-stage shutdown
java.lang.InterruptedException
02/04 14:01:49.728 [pool-12-thread-6] INFO  TransactionProcessingPipelineImpl:158 - broadcast-stage shutdown
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.ArrayBlockingQueue.put(ArrayBlockingQueue.java:353)
	at com.iota.iri.crypto.batched.BatchedBCTCurl.submitHashingRequest(BatchedBCTCurl.java:58)
	at com.iota.iri.network.pipeline.HashingStage.process(HashingStage.java:33)
	at com.iota.iri.network.pipeline.TransactionProcessingPipelineImpl.hashAndValidate(TransactionProcessingPipelineImpl.java:221)
	at com.iota.iri.network.pipeline.TransactionProcessingPipelineImpl.lambda$addStage$0(TransactionProcessingPipelineImpl.java:134)
	at java.lang.Thread.run(Thread.java:748)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.ArrayBlockingQueue.put(ArrayBlockingQueue.java:353)
	at com.iota.iri.network.pipeline.TransactionProcessingPipelineImpl.process(TransactionProcessingPipelineImpl.java:186)
	at com.iota.iri.network.neighbor.impl.NeighborImpl.handleMessage(NeighborImpl.java:157)
	at com.iota.iri.network.neighbor.impl.NeighborImpl.read(NeighborImpl.java:105)
	at com.iota.iri.network.neighbor.impl.NeighborImpl.read(NeighborImpl.java:102)
	at com.iota.iri.network.NeighborRouterImpl.handleRead(NeighborRouterImpl.java:400)
	at com.iota.iri.network.NeighborRouterImpl.route(NeighborRouterImpl.java:215)
02/04 14:02:18.046 [pool-12-thread-4] INFO  TransactionProcessingPipelineImpl:158 - reply-stage shutdown
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
02/04 14:02:18.048 [pool-12-thread-5] INFO  TransactionProcessingPipelineImpl:158 - received-stage shutdown
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
02/04 14:01:49.729 [pool-12-thread-1] ERROR TransactionProcessingPipelineImpl:218 - unable to put processing context into hashing stage. reason: null
02/04 14:02:18.053 [Neighbor Router] INFO  NeighborRouterImpl:240 - neighbor router stopped
02/04 14:02:38.397 [Shutdown Hook] INFO  Tangle:78 - Releasing all caches...


02/04 14:05:32.432 [Shutdown Hook] INFO  Tangle:81 - Shutting down Tangle Persistence Providers... 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f795b779aea, pid=1, tid=0x00007f79409ce700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [librocksdbjni9051936110232332458.so+0x24baea]  rocksdb::DBImpl::GetImpl(rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, rocksdb::PinnableSlice*, bool*, rocksdb::ReadCallback*, bool*)+0x1ca
#
# Core dump written. Default location: /iri/data/core or core.1
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

[error occurred during error reporting , id 0xb]
```

### PR DESCRIPTION
**Pull request by GalRogozinski**
# Description

Changes the queues that we use for networking to have unlimited capacity

Fixes #1742 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

# How Has This Been Tested?

IRI was synced without needing to restart and no error appeared
It should be noted that I did notice a slow down in syncing

I think we should investigate going back to array based queues later on to speed things up

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by kwek20** [comment]
Hmm yes as this will allocate memory for every add and remove, it is considerably heavier. I am not sure if its worth the drawbacks just to fix a minor shutdown error

**Comment by GalRogozinski** [comment]
@kwek20 
Should have made it clearer on the issue
It also causes syncing problems and clogs the node it caused devnet compass to stop and thus killed the network (see ops-general in our internal slack), which is quite worrisome

Having said this, I agree with you...
It is also why I was reluctant to merge my fix, that was sitting on my branch for quite a while (you can see a reference to it in the issue).

My plan was to open another issue about changing it back to array based queue but to solve the deadlock. If you think you can have a look in the meanwhile and create the real solution it will be great. I have no idea how easy/hard it will be...

**Comment by kwek20** [comment]
I have asked @luca-moser for feedback on the original decision. Might give us some insights.
Either way, making it volatile would reduce speed across threads quite a bit, as every time it changes, it writes all fields in the TVM to global memory. so AtomicBool is actually nicer here.

I will open the issue to solve this properly

**Comment by luca-moser** [comment]
As per Brord's request: the sole reason I made them ArrayBlockingQueues was to have them bounded. I believe the source problem is the incorrect handling of shutdown events in conjunction in which order the different stages are interrupted. The first crash log from the linked issue suggests that there's no real interrupt handler in the BCTCurl (didn't have a closer look at the code though).

**Pull request merged**
