### PR TITLE
Update snapshot to 16:00 UTC 20180429

### PR DESCRIPTION
**Pull request by alon-e**
This is the proposed announced snapshot for milestone 426522.

To make this snapshot as smooth, and as safe as possible, we have provided several scripts for the community to independently validate the snapshot and post the results here.
We suggest the community to do so before 2018/04/29 23:00 UTC, when the coordinator will restart and a new IRI version will be published.

How to Validate

In order to validate this snapshot, we have provided a script for you to run and validate the Snapshot yourself.

Obviously, the main assumption is that you have a fully synced node with the latestSolidSubtangleMilestoneIndex at 426522 , and that you're at least a beginner developer.

1. Follow installation instuctions in: https://github.com/iotaledger/snapshot-validator

2. Run and Validate: Adjust validation script for your node host/port (Step 3. in `snapshot-validator`) and run with `npm start`

```var snapshotUrl = 'https://raw.githubusercontent.com/alon-e/iri/c62f459fa37698d387cc6067b6aa89427a3db8f7/src/main/resources/snapshotMainnet.txt';```

3. Post your results as a comment below. (similar to #512)

### CODE REVIEW

**Comment by nuriel77** [comment]
```sh
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by TeeVeeEss** [comment]
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by OleWouters** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by Johnny-Milkshakes** [comment]
BALANCE CORRECT: true
VALIDATING SNAPSHOT ENTRIES: 315553
LATEST STATE EQUALS SNAPSHOT: true

**Comment by Smie85** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by rnsnbrnk** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by tolotos-rgu** [comment]
2nd Node:
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by LoranTIm** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by frohal** [comment]
$ node validate.js
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by quxch** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by KeenHero** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by tawago** [comment]
woop! woop!
> node validate.js

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by lambtho12** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by hellsingfan** [comment]
BALANCE CORRECT: true
VALIDATING SNAPSHOT ENTRIES: 315553
LATEST STATE EQUALS SNAPSHOT: true

**Comment by maxi656** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by PerfectStorm85** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by CarlsbergFTW** [comment]
hello, i'm getting ALOT and i mean ALOT of errors like this one:
> snapshot-validator@1.0.0 start /var/lib/iri/target/ixi/snapshot-validator
> node validate.js

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
FATAL ERROR: Balance incorrect for:  999999999999999999999999999999999999999999999999999999999999999999999999999999999
Balance (proposed snapshot vs. local):  22364358 22364359
FATAL ERROR: Balance incorrect for:  99ACHJDNKKZEGPWGX9ZDZDJBXEMSCLCRHYMECJCIJPDQGVGNBT9AZSHUR9WOCKUYPLWGGFMUEVTHOACVX
Balance (proposed snapshot vs. local):  81500000 NaN
FATAL ERROR: Balance incorrect for:  99ACLSKPQQX9TEHQPSKICCMYNHRQSAEMIHWSICICSFLGBP9BUMJHDIRFGDCKKZFRLXRRDVVLCWDFKWDMB
Balance (proposed snapshot vs. local):  20479000 NaN
FATAL ERROR: Balance incorrect for:  99BCF9ZEMWCUGSYYCFQLCSWTYWWZCIQMENJAGHDLJ9UTIHBYPYVYRXSOSNIVYYFZZ9GFFZJKICHJLOLHC
Balance (proposed snapshot vs. local):  78522250 NaN

**Comment by Xermio** [comment]
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by PatriQ94** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by andymarkwart** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by svenger87** [comment]
Node 1: 
`BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true`
Node 2:
`BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true`

**Comment by cyclux** [comment]
```BALANCE CORRECT: true
VALIDATING SNAPSHOT ENTRIES: 315553
LATEST STATE EQUALS SNAPSHOT: true```

**Comment by schnico** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by sagmnst** [comment]
BALANCE CORRECT: true
VALIDATING SNAPSHOT ENTRIES: 315553
LATEST STATE EQUALS SNAPSHOT: true

**Comment by NetWalkerGit** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by lluisin** [comment]
> node validate.js

BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by darrenolson** [comment]
Valid for 6 nodes
BALANCE CORRECT: true
VALIDATING SNAPSHOT ENTRIES: 315553
LATEST STATE EQUALS SNAPSHOT: true

**Comment by kriptor** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by cym00n** [comment]
```
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true
```

**Comment by oyren** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by markschwed** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by LoneStar22** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by VMataV** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by olazpreton** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by olazpreton** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by malfidev** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by SeeUnsharp** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by ThaPhil** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by GP1992** [comment]
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  315553
LATEST STATE EQUALS SNAPSHOT:  true

**Comment by Niuran78** [comment]
Node1:
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

Node 2:
BALANCE CORRECT:  true
VALIDATING SNAPSHOT ENTRIES:  260629
LATEST STATE EQUALS SNAPSHOT:  true

**Pull request merged**
